
services:
  web:
    image: "${CUMORAH_IMAGE:-ghcr.io/buildzion/cumorah}:${CUMORAH_TAG:-latest}"
    ports:
      - "${LISTEN_PORT:-8000}:8000"
    environment:
      PYTHONPATH: "/host/python"
      DOCKER_TEMPLATE_DIR: "/host/templates"
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE:-cumorah.settings.production}"
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: "${DATABASE_URL:-postgres://cumorah:cumorah@postgres/cumorah}"
    volumes:
      - ./dockerdata/python:/host/python
      - ./dockerdata/templates:/host/templates
    depends_on:
      - postgres

  postgres:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: cumorah
      POSTGRES_USER: cumorah
      POSTGRES_PASSWORD: cumorah
    volumes:
      - ./dockerdata/postgres:/var/lib/postgresql/data


